// plasmic-init.js
import { initPlasmicLoader } from "@plasmicapp/loader-nextjs";
import { CustomScroll } from "./components/effects/animation/CustomScroll";
import GradualBlur from './components/effects/visual/gradualBlur';
import { GravityWrapper } from "./components/effects/physics/gravity"
import { Object } from "./components/effects/physics/object"
import { CustomCode } from "./components/code/customCode"
import { Planets } from "./components/three/scenes/planets"
import StarFieldLoader from "./components/loaders/starFieldLoader";

// import { StickerPeel } from "./components/effects/StickerPeel";
// import ThreeCanvas from "./components/three/canvas/ThreeCanvas"
// import MapTilerMap from "./components/maps/map"

import dynamic from 'next/dynamic';

export const PLASMIC = initPlasmicLoader({
  projects: [
    {
      id: "rdUbbFyBk8F7AduKnQeuGL",
      token: "ULH0HD4xX1eA3r6fDn3O94tMMi7NTqtzBvCgDVS1NZ9r9VMmmwCgYf9AEQxXfQPOjxPE3sE4dXzfAqCgbw",
    },
  ],
  preview: true,
});

PLASMIC.registerComponent(CustomCode, {
  name: "CustomCode",
  displayName: "Custom Code",
  description: "A wrapper component for passing props using custom code",
  props: {
    children: {
      type: "slot",
      defaultValue: {
        type: "text",
        value: "Add children here",
      },
    },
    className: {
      type: "string",
      description: "Additional CSS classes",
    },
    code: {
      type: "string",
      displayName: "Code",
      description: "JavaScript code executed on mount and when dependencies change",
      defaultValue: `// Example:
        setValue({
          hr1: 0,
          hr2: 3,
          min1: 3,
          min2: 0,
        });`,
        control: "code",
    },
    deps: {
      type: "array",
      displayName: "Dependencies",
      description:"Values that trigger the code to re-run when changed",
      itemType: {
        type: "string",
      },
      defaultValue: [],
    },
  },
  importPath: "./components/code/customCode",
  isDefaultExport: false,
})


PLASMIC.registerComponent(GravityWrapper, {
  name: "GravityWrapper",
  displayName: "Gravity Wrapper",
  description: "A wrapper component for creating physics-based gravity animations with Matter.js",
  props: {
    children: {
      type: "slot",
      defaultValue: {
        type: "text",
        value: "Add objects here",
      },
    },
    debug: {
      type: "boolean",
      defaultValue: false,
      description: "Show physics bodies and vertices overlay for debugging",
    },
    gravity: {
      type: "object",
      defaultValue: { x: 0, y: 1 },
      description: "Gravity direction vector (x, y). Default is downward: {x: 0, y: 1}",
    },
    resetOnResize: {
      type: "boolean",
      defaultValue: true,
      description: "Reset physics world when window resizes",
    },
    grabCursor: {
      type: "boolean",
      defaultValue: true,
      description: "Show grab/grabbing cursor when interacting with bodies",
    },
    addTopWall: {
      type: "boolean",
      defaultValue: true,
      description: "Add invisible wall at top to prevent objects from escaping",
    },
    autoStart: {
      type: "boolean",
      defaultValue: true,
      description: "Automatically start the physics simulation on mount",
    },
    className: {
      type: "string",
      description: "Additional CSS classes",
    },
  },
  importPath: "./components/effects/physics/gravity",
  isDefaultExport: false,
});

// Register the Object (MatterBody wrapper) component
PLASMIC.registerComponent(Object, {
  name: "PhysicsObject",
  displayName: "Physics Object",
  description: "A physics-enabled object that responds to gravity and collisions",
  props: {
    children: {
      type: "slot",
      defaultValue: {
        type: "box",
        styles: {
          width: "80px",
          height: "80px",
          background: "#3b82f6",
          borderRadius: "8px",
        },
      },
    },
    // Position props
    x: {
      type: "string",
      defaultValue: "50%",
      description: "X position (number or percentage string like '50%')",
    },
    y: {
      type: "string",
      defaultValue: "20%",
      description: "Y position (number or percentage string like '20%')",
    },
    angle: {
      type: "number",
      defaultValue: 0,
      description: "Initial rotation angle in degrees",
    },
    // Body type
    bodyType: {
      type: "choice",
      options: ["rectangle", "circle", "svg"],
      defaultValue: "rectangle",
      description: "Physics body shape type",
    },
    // Interaction
    isDraggable: {
      type: "boolean",
      defaultValue: true,
      description: "Whether the body can be dragged with the mouse",
    },
    // Physics properties - Basic
    friction: {
      type: "number",
      defaultValue: 0.1,
      min: 0,
      max: 1,
      description: "Surface friction (0-1). Higher = more friction",
    },
    restitution: {
      type: "number",
      defaultValue: 0.1,
      min: 0,
      max: 1,
      description: "Bounciness (0-1). Higher = more bouncy",
    },
    density: {
      type: "number",
      defaultValue: 0.001,
      description: "Density/weight. Higher = heavier",
    },
    isStatic: {
      type: "boolean",
      defaultValue: false,
      description: "If true, object won't move but can be collided with",
    },
    // Air resistance
    frictionAir: {
      type: "number",
      defaultValue: 0.01,
      min: 0,
      max: 1,
      description: "Air resistance (0-1). Higher = slower movement",
    },
    frictionStatic: {
      type: "number",
      defaultValue: 0.5,
      min: 0,
      max: 1,
      description: "Static friction before object starts moving",
    },
    // Advanced physics
    mass: {
      type: "number",
      description: "Mass of the body (auto-calculated if not set)",
      advanced: true,
    },
    isSleeping: {
      type: "boolean",
      defaultValue: false,
      description: "Whether body starts in sleep state",
      advanced: true,
    },
    motion: {
      type: "number",
      defaultValue: 0,
      description: "Amount of motion in the body",
      advanced: true,
    },
    sleepThreshold: {
      type: "number",
      defaultValue: 60,
      description: "Threshold for putting body to sleep",
      advanced: true,
    },
    restitutionThreshold: {
      type: "number",
      defaultValue: 4,
      description: "Velocity threshold for restitution",
      advanced: true,
    },
    slop: {
      type: "number",
      defaultValue: 0.05,
      description: "Allowed penetration amount for stability",
      advanced: true,
    },
    timeScale: {
      type: "number",
      defaultValue: 1,
      description: "Time scale for this body's simulation",
      advanced: true,
    },
    // SVG specific
    sampleLength: {
      type: "number",
      defaultValue: 15,
      description: "Sampling distance for SVG path vertices (only for SVG bodyType)",
      advanced: true,
    },
    // Styling
    className: {
      type: "string",
      description: "Additional CSS classes",
    },
  },
  importPath: "./components/effects/physics/object",
  isDefaultExport: false,
});

// PLASMIC.registerComponent(MapTilerMap, {
//   name: 'MapTilerMap',
//   displayName: 'MapTiler Map',
//   description: 'Interactive map powered by MapTiler and MapLibre GL JS',
//   importPath: './MapTilerMap',
//   props: {
//     apiKey: {
//       type: 'string',
//       displayName: 'API Key',
//       description: 'Your MapTiler API key from https://cloud.maptiler.com',
//       defaultValue: 'YOUR_MAPTILER_API_KEY',
//     },
//     mapStyle: {
//       type: 'choice',
//       displayName: 'Map Style',
//       description: 'MapTiler map style to use',
//       options: [
//         { value: 'streets-v2', label: 'Streets' },
//         { value: 'satellite', label: 'Satellite' },
//         { value: 'hybrid', label: 'Hybrid' },
//         { value: 'outdoor-v2', label: 'Outdoor' },
//         { value: 'winter-v2', label: 'Winter' },
//         { value: 'basic-v2', label: 'Basic' },
//         { value: 'basic-v2-dark', label: 'Basic' },
//         { value: 'bright-v2', label: 'Bright' },
//         { value: 'pastel', label: 'Pastel' },
//         { value: 'topo-v2', label: 'Topographic' },
//         { value: 'voyager', label: 'Voyager' },
//         { value: 'toner-v2', label: 'Toner' },
//         { value: 'backdrop', label: 'Backdrop' },
//         { value: 'dataviz', label: 'Data Visualization' },
//         { value: 'ocean', label: 'Ocean' },
//       ],
//       defaultValue: 'streets-v2',
//     },
//     longitude: {
//       type: 'number',
//       displayName: 'Longitude',
//       description: 'Center longitude coordinate',
//       defaultValue: -81.9748,
//     },
//     latitude: {
//       type: 'number',
//       displayName: 'Latitude',
//       description: 'Center latitude coordinate',
//       defaultValue: 33.4735,
//     },
//     zoom: {
//       type: 'number',
//       displayName: 'Zoom Level',
//       description: 'Map zoom level (0-22)',
//       defaultValue: 12,
//       min: 0,
//       max: 22,
//       step: 0.1,
//     },
//     pitch: {
//       type: 'number',
//       displayName: 'Pitch',
//       description: 'Map pitch/tilt angle in degrees (0-85)',
//       defaultValue: 0,
//       min: 0,
//       max: 85,
//       step: 1,
//     },
//     bearing: {
//       type: 'number',
//       displayName: 'Bearing',
//       description: 'Map rotation bearing in degrees (0-360)',
//       defaultValue: 0,
//       min: 0,
//       max: 360,
//       step: 1,
//     },
//     minZoom: {
//       type: 'number',
//       displayName: 'Min Zoom',
//       description: 'Minimum zoom level allowed',
//       defaultValue: 0,
//       min: 0,
//       max: 22,
//       step: 1,
//     },
//     maxZoom: {
//       type: 'number',
//       displayName: 'Max Zoom',
//       description: 'Maximum zoom level allowed',
//       defaultValue: 22,
//       min: 0,
//       max: 22,
//       step: 1,
//     },
//     width: {
//       type: 'string',
//       displayName: 'Width',
//       description: 'Map container width (CSS value)',
//       defaultValue: '100%',
//     },
//     height: {
//       type: 'string',
//       displayName: 'Height',
//       description: 'Map container height (CSS value)',
//       defaultValue: '400px',
//     },
//     showControls: {
//       type: 'boolean',
//       displayName: 'Show Controls',
//       description: 'Show zoom and rotation controls',
//       defaultValue: true,
//     },
//     showScale: {
//       type: 'boolean',
//       displayName: 'Show Scale',
//       description: 'Show map scale indicator',
//       defaultValue: false,
//     },
//     interactive: {
//       type: 'boolean',
//       displayName: 'Interactive',
//       description: 'Enable map interactions (zoom, pan, rotate)',
//       defaultValue: true,
//     },
//     markers: {
//       type: 'array',
//       displayName: 'Markers',
//       description: 'Array of marker objects',
//       defaultValue: [],
//       itemType: {
//         type: 'object',
//         fields: {
//           longitude: {
//             type: 'number',
//             displayName: 'Longitude',
//           },
//           latitude: {
//             type: 'number',
//             displayName: 'Latitude',
//           },
//           color: {
//             type: 'string',
//             displayName: 'Color',
//             defaultValue: '#3b82f6',
//           },
//           popup: {
//             type: 'string',
//             displayName: 'Popup Text',
//           },
//         },
//       },
//     },
//     className: {
//       type: 'string',
//       displayName: 'CSS Class',
//       description: 'Additional CSS class name',
//       defaultValue: '',
//     },
//   },
//   importPath: "./components/maps/map",
//   isDefaultExport: true,
// })

// const GuitarLoader = dynamic(() => import('./components/loaders/GuitarLoader'), { ssr: false });
// PLASMIC.registerComponent(GuitarLoader, {
//   name: "Guitar Loader",
//   displayName: "Guitar Loader",
//   description: "A Guitar loader to show loading progress",
//   props: {
//     children: {
//       type: "slot",
//       defaultValue: {
//         type: "text",
//         value: "Content to load",
//       },
//     },
//     showLoader: {
//       type: "boolean",
//       displayName: "Display Loader?",
//       defaultValue: true,
//     }
//   },
//   styleProps: [
//     "width",
//     "height",
//     "minWidth",
//     "maxWidth", 
//     "minHeight",
//     "maxHeight",
//     "position",
//     "top",
//     "left",
//     "right",
//     "bottom",
//     "zIndex",
//     "display",
//     "flexDirection",
//     "flexWrap",
//     "justifyContent",
//     "alignItems",
//     "gap",
//     "padding",
//     "margin",
//     "background",
//     "backgroundColor",
//     "border",
//     "borderRadius",
//     "overflow",
//   ],
//   importPath: "./components/loaders/GuitarLoader",
//   isDefaultExport: true,
// })

// PLASMIC.registerComponent(StickerPeel, {
//   name: "StickerPeel",
//   displayName: "Sticker Peel",
//   description: "Sticker peel effect for images",

//   props: {
//     imageSrc: {
//       type: "imageUrl",
//       displayName: "Image",
//       description: "Image used as the sticker"
//     },
//     rotate: {
//       type: "number",
//       displayName: "Rotate",
//       defaultValue: 30
//     },
//     peelBackHoverPct: {
//       type: "number",
//       displayName: "Peel Back (Hover) %",
//       defaultValue: 30
//     },
//     peelBackActivePct: {
//       type: "number",
//       displayName: "Peel Back (Active) %",
//       defaultValue: 40
//     },
//     peelEasing: {
//       type: "string",
//       displayName: "Peel Easing",
//       defaultValue: "power3.out",
//       enumValues: ["power1.out", "power2.out", "power3.out", "power4.out", "expo.out"]
//     },
//     peelHoverEasing: {
//       type: "string",
//       displayName: "Peel Hover Easing",
//       defaultValue: "power2.out",
//       enumValues: ["power1.out", "power2.out", "power3.out", "power4.out", "expo.out"]
//     },
//     width: {
//       type: "number",
//       displayName: "Width (px)",
//       defaultValue: 200
//     },
//     height: {
//       type: "number",
//       displayName: "Height (px)",
//       defaultValue: 200
//     },
//     shadowIntensity: {
//       type: "number",
//       displayName: "Shadow Intensity",
//       defaultValue: 0.6
//     },
//     lightingIntensity: {
//       type: "number",
//       displayName: "Lighting Intensity",
//       defaultValue: 0.1
//     },
//     peelDirection: {
//       type: "number",
//       displayName: "Peel Direction (deg)",
//       defaultValue: 0
//     },
//     className: {
//       type: "class",
//       displayName: "CSS Class",
//     },
//   },
//   importPath: "./components/effects/StickerPeel",
//   isDefaultExport: false,
// });


// PLASMIC.registerComponent(ThreeCanvas, {
//   name: "TheeCanvas",
//   displayName: "Three.js Scroll Effect",
//   description: "Animate camera and 3D objects with initial positions, load effects, and click-triggered effects",
//   props: {

//     initialPositions: {
//       type: "array",
//       displayName: "Initial Positions",
//       description: "Set initial position, rotation, and FOV for objects",
//       itemType: {
//         type: "object",
//         fields: {
//           object: {
//             type: "string",
//             displayName: "Object Name",
//             description: "Name of the object (e.g., 'camera')",
//             defaultValue: "camera",
//           },
//           position: {
//             type: "object",
//             displayName: "Position",
//             description: "Position {x, y, z}",
//             fields: {
//               x: { type: "number", defaultValue: 0 },
//               y: { type: "number", defaultValue: 1 },
//               z: { type: "number", defaultValue: 1 }
//             }
//           },
//           rotation: {
//             type: "object",
//             displayName: "Rotation",
//             description: "Rotation {x, y, z} in radians",
//             fields: {
//               x: { type: "number", defaultValue: 0 },
//               y: { type: "number", defaultValue: 0 },
//               z: { type: "number", defaultValue: 0 }
//             }
//           },
//           fov: {
//             type: "number",
//             displayName: "FOV (camera only)",
//             description: "Field of view for camera",
//             defaultValue: 25,
//           }
//         }
//       }
//     },
//     loadEffect: {
//       type: "array",
//       displayName: "Load Effects",
//       description: "Animations triggered when scene loads (progress reaches 100%)",
//       itemType: {
//         type: "object",
//         fields: {
//           object: {
//             type: "string",
//             displayName: "Object Name",
//             description: "Name of the object (e.g., 'camera')",
//             defaultValue: "camera",
//           },
//           duration: {
//             type: "number",
//             displayName: "Duration (ms)",
//             description: "Animation duration in milliseconds",
//             defaultValue: 1000,
//           },
//           delay: {
//             type: "number",
//             displayName: "Delay (ms)",
//             description: "Delay before animation starts",
//             defaultValue: 0,
//           },
//           easingFunction: {
//             type: "choice",
//             options: [
//               "linear",
//               "easeInQuad",
//               "easeOutQuad",
//               "easeInOutQuad",
//               "easeInCubic",
//               "easeOutCubic",
//               "easeInOutCubic",
//               "easeInQuart",
//               "easeOutQuart",
//               "easeInOutQuart",
//               "easeInQuint",
//               "easeOutQuint",
//               "easeInOutQuint",
//               "easeInSine",
//               "easeOutSine",
//               "easeInOutSine",
//               "easeInExpo",
//               "easeOutExpo",
//               "easeInOutExpo",
//               "easeInCirc",
//               "easeOutCirc",
//               "easeInOutCirc",
//               "easeInBack",
//               "easeOutBack",
//               "easeInOutBack",
//               "easeInElastic",
//               "easeOutElastic",
//               "easeInOutElastic",
//               "easeInBounce",
//               "easeOutBounce",
//               "easeInOutBounce",
//             ],
//             displayName: "Easing Function",
//             defaultValue: "linear",
//           },
//           position: {
//             type: "object",
//             displayName: "Target Position",
//             description: "End position {x, y, z}",
//             fields: {
//               x: { type: "number", defaultValue: 0 },
//               y: { type: "number", defaultValue: 1 },
//               z: { type: "number", defaultValue: 1 }
//             }
//           },
//           rotation: {
//             type: "object",
//             displayName: "Target Rotation",
//             description: "End rotation {x, y, z} in radians",
//             fields: {
//               x: { type: "number", defaultValue: 0 },
//               y: { type: "number", defaultValue: 0 },
//               z: { type: "number", defaultValue: 0 }
//             }
//           },
//           fov: {
//             type: "number",
//             displayName: "Target FOV",
//             description: "End field of view (camera only)",
//             defaultValue: 25,
//           }
//         }
//       }
//     },
//     clickEffects: {
//       type: "array",
//       displayName: "Click Effects",
//       description: "Animations triggered by clicking elements with specific IDs",
//       itemType: {
//         type: "object",
//         fields: {
//           object: {
//             type: "string",
//             displayName: "Object Name",
//             description: "Name of the object (e.g., 'camera')",
//             defaultValue: "camera",
//           },
//           triggerId: {
//             type: "string",
//             displayName: "Trigger Element ID",
//             description: "ID of the element that triggers this effect when clicked",
//             defaultValue: "",
//           },
//           duration: {
//             type: "number",
//             displayName: "Duration (ms)",
//             description: "Animation duration in milliseconds",
//             defaultValue: 1000,
//           },
//           delay: {
//             type: "number",
//             displayName: "Delay (ms)",
//             description: "Delay before animation starts",
//             defaultValue: 0,
//           },
//           easingFunction: {
//             type: "choice",
//             options: [
//               "linear",
//               "easeInQuad",
//               "easeOutQuad",
//               "easeInOutQuad",
//               "easeInCubic",
//               "easeOutCubic",
//               "easeInOutCubic",
//               "easeInQuart",
//               "easeOutQuart",
//               "easeInOutQuart",
//               "easeInQuint",
//               "easeOutQuint",
//               "easeInOutQuint",
//               "easeInSine",
//               "easeOutSine",
//               "easeInOutSine",
//               "easeInExpo",
//               "easeOutExpo",
//               "easeInOutExpo",
//               "easeInCirc",
//               "easeOutCirc",
//               "easeInOutCirc",
//               "easeInBack",
//               "easeOutBack",
//               "easeInOutBack",
//               "easeInElastic",
//               "easeOutElastic",
//               "easeInOutElastic",
//               "easeInBounce",
//               "easeOutBounce",
//               "easeInOutBounce",
//             ],
//             displayName: "Easing Function",
//             defaultValue: "linear",
//           },
//           position: {
//             type: "object",
//             displayName: "Target Position",
//             description: "End position {x, y, z}",
//             fields: {
//               x: { type: "number", defaultValue: 0 },
//               y: { type: "number", defaultValue: 1 },
//               z: { type: "number", defaultValue: 1 }
//             }
//           },
//           rotation: {
//             type: "object",
//             displayName: "Target Rotation",
//             description: "End rotation {x, y, z} in radians",
//             fields: {
//               x: { type: "number", defaultValue: 0 },
//               y: { type: "number", defaultValue: 0 },
//               z: { type: "number", defaultValue: 0 }
//             }
//           },
//           fov: {
//             type: "number",
//             displayName: "Target FOV",
//             description: "End field of view (camera only)",
//             defaultValue: 25,
//           }
//         }
//       }
//     },
//     className: {
//       type: "class",
//       displayName: "CSS Class",
//     },
//   },
//   styleProps: [
//     "width",
//     "height",
//     "minWidth",
//     "maxWidth", 
//     "minHeight",
//     "maxHeight",
//     "position",
//     "top",
//     "left",
//     "right",
//     "bottom",
//     "zIndex",
//     "display",
//     "flexDirection",
//     "flexWrap",
//     "justifyContent",
//     "alignItems",
//     "gap",
//     "padding",
//     "margin",
//     "background",
//     "backgroundColor",
//     "border",
//     "borderRadius",
//     "overflow",
//   ],
//   importPath: "../components/three/canvas/ThreeCanvas",
//   isDefaultExport: true,
// });

PLASMIC.registerComponent(Planets, {
  name: "PlanetScene",
  displayName: "Planet Scene",
  props: {
    className: {
      type: "string",
      description: "Additional CSS classes",
    },
    id: {
      type: "string",
      displayName: "id"
    },
  },
  importPath: "./components/three/scenes/planets",
  isDefaultExport: false,
})

PLASMIC.registerComponent(StarFieldLoader, {
  name: "StarFieldLoader",
  displayName: "Star Field Loader",
  props: {
    className: {
      type: "string",
      description: "Additional CSS classes",
    },
    id: {
      type: "string",
      displayName: "id"
    },
  },
  importPath: "./components/loader/starFieldLoader",
  isDefaultExport: true,
})

PLASMIC.registerComponent(GradualBlur, {
  name: 'GradualBlur',
  displayName: "Gradual Blur",
  description: "Gradual Blur Effect",
  props: {
    preset: {
      type: 'choice',
      options: [
        '', 'top', 'bottom', 'left', 'right',
        'subtle', 'intense', 'smooth', 'sharp',
        'header', 'footer', 'sidebar', 'page-header', 'page-footer'
      ],
      defaultValue: ''
    },
    position: {
      type: 'choice',
      options: ['top', 'bottom', 'left', 'right'],
      defaultValue: 'bottom'
    },
    strength: { type: 'number', defaultValue: 2 },
    height: { type: 'string', defaultValue: '6rem' },
    width: { type: 'string' },
    divCount: { type: 'number', defaultValue: 5 },
    exponential: { type: 'boolean', defaultValue: false },
    zIndex: { type: 'number', defaultValue: 1000 },
    animated: { type: 'choice', options: [false, true, 'scroll'], defaultValue: false },
    duration: { type: 'string', defaultValue: '0.3s' },
    easing: { type: 'choice', options: ['linear', 'ease-in', 'ease-out', 'ease-in-out'], defaultValue: 'ease-out' },
    opacity: { type: 'number', defaultValue: 1 },
    curve: { type: 'choice', options: ['linear', 'bezier', 'ease-in', 'ease-out', 'ease-in-out'], defaultValue: 'linear' },
    responsive: { type: 'boolean', defaultValue: false },
    target: { type: 'choice', options: ['parent', 'page'], defaultValue: 'parent' },
    className: { type: 'string' },
    style: { type: 'object' },
    hoverIntensity: { type: 'number' },
  },
  importPath: './components/effects/visual/gradualBlur',
  isDefaultExport: true,
});


// Plasmic Registration
PLASMIC.registerComponent(CustomScroll, {
  name: "CustomScroll",
  displayName: "Custom Scroll Effect",
  description: "Animate any CSS properties based on scroll with multiple breakpoints, easing functions, and click-triggered effects",
  props: {
    text: {
      type: "string",
      displayName: "Text",
      description: "Use text instead of elements.",
      defaultValue: "",
    },
    animateChars: {
      type: "boolean",
      displayName: "Animate Characters",
      description: "Animate each character of the provided text",
      defaultValue: false,
      hidden: (props) => props.text === "" && props.animateWords !== true,
    },
    animateWords: {
      type: "boolean",
      displayName: "Animate Characters",
      description: "Animate each character of the provided text",
      defaultValue: false,
      hidden: (props) => props.text === "" && props.animateChars !== true,
    },
    // characterDelayOffset: {
    //   type: "number",
    //   diplayName: "Character Delay Offset (ms)",
    //   description: "delay characters to be animated after proceeding character.",
    //   defaultValue: 0,
    //   hidden: (props) => props.animateChars === false,
    // },
    children: {
      type: "slot",
      defaultValue: {
        type: "text",
        value: "Scroll to animate",
      },
      hidden: (props) => props.text !== "",
    },
    id: {
      type: "string",
      displayName: "id"
    },
    // usePropValue: {
    //   type: "boolean",
    //   defaultValue: false,
    //   displayName: "Use Prop Value",
    //   description: "Should the component replace children with the value passed by the custom code component (requires parent to be custom code component)"
    // },
    // useSpecificProp: {
    //   type: "boolean",
    //   defaultValue: false,
    //   displayName: "Use Specific Prop",
    //   description: "Should the component use only one specific prop provided by the custom code component. (requires parent to be custom code component)",
    //   hidden: (props) => props.usePropValue !== true,
    // },
    // propToUse:{
    //   type: "string",
    //   defaultValue: "",
    //   displayName: "Prop To Use",
    //   description: "which specific prop will be used. (requires parent to be custom code component)",
    //   hidden: (props) => props.useSpecificProp !== true,
    // },
    position: {
      type: "choice",
      options: ["relative", "absolute", "fixed", "sticky"],
      defaultValue: "relative",
      displayName: "Position"
    },
    applyToChildren: {
      type: "boolean",
      displayName: "Apply Animation To Children",
      description: "Animate children instead of this element",
      defaultValue: false,
    },
    cascadeDelay: {
      type: "number",
      displayName: "Cascading Delay (ms)",
      description: "Add a delay to offset when each child animation starts.",
      defaultValue: 0,
      hidden: (props) => props.applyToChildren === false,
    },
    initialStyles: {
      type: "array",
      displayName: "Initial Animation Styles",
      description: "Define the initial values of styles that animations modify",
      itemType: {
        type: "object",
        fields: {
          property: {
            type: "choice",
            displayName: "CSS Property",
            description: "Select which CSS property to initialize",
            options: [
              "top",
              "left",
              "right",
              "bottom",
              "width",
              "height",
              "opacity",
              "borderRadius",
              "scale",
              "rotate",
              "translateX",
              "translateY",
              "translateZ",
              "scaleX",
              "scaleY",
              "scaleZ",
              "rotateX",
              "rotateY",
              "rotateZ",
              "skewX",
              "skewY",
              "backgroundColor",
              "color",
              "fontSize",
              "letterSpacing",
              "lineHeight",
              "padding",
              "margin",
              "borderWidth",
              "boxShadow",
              "textShadow",
              "filter",
              "backdropFilter",
            ],
            defaultValue: "opacity",
          },
          startValue: {
            type: "string",
            displayName: "Start Value",
            description: "Initial value (e.g., '100px', '0', '1', '45deg', '#ff0000')",
            defaultValue: "0",
          }
        }
      }
    },
    loadEffect: {
      type: "object",
      displayName: "On Load Effect",
      description: "Define effects that trigger when application loads",
      fields: {
        duration: {  // Changed from itemType to duration
          type: "number",
          displayName: "Duration (ms)",
          description: "How long should this effect animate",
          defaultValue: 1000,
        },
        delay: {  // Changed from itemType to delay
          type: "number",
          displayName: "Delay (ms)",
          description: "How long should this effect wait to animate",
          defaultValue: 0,
        },
        easingFunction: {  // Changed from itemType to easingFunction
          type: "choice",
          options: [
            "linear",
            "easeInQuad",
            "easeOutQuad",
            "easeInOutQuad",
            "easeInCubic",
            "easeOutCubic",
            "easeInOutCubic",
            "easeInQuart",
            "easeOutQuart",
            "easeInOutQuart",
            "easeInQuint",
            "easeOutQuint",
            "easeInOutQuint",
            "easeInSine",
            "easeOutSine",
            "easeInOutSine",
            "easeInExpo",
            "easeOutExpo",
            "easeInOutExpo",
            "easeInCirc",
            "easeOutCirc",
            "easeInOutCirc",
            "easeInBack",
            "easeOutBack",
            "easeInOutBack",
            "easeInElastic",
            "easeOutElastic",
            "easeInOutElastic",
            "easeInBounce",
            "easeOutBounce",
            "easeInOutBounce",
          ],
          defaultValue: "easeInOutExpo",
          displayName: "On Load Easing Function",
          description: "Timing function for the on load animation.",
        },
        styles: {  // Changed from itemType to styles
          type: "array",
          displayName: "On Load Animation Styles",
          description: "Define the values of styles to modify on load",
          itemType: {
            type: "object",
            fields: {
              property: {
                type: "choice",
                displayName: "CSS Property",
                description: "Select which CSS property to initialize",
                options: [
                  "top",
                  "left",
                  "right",
                  "bottom",
                  "width",
                  "height",
                  "opacity",
                  "borderRadius",
                  "scale",
                  "rotate",
                  "translateX",
                  "translateY",
                  "translateZ",
                  "scaleX",
                  "scaleY",
                  "scaleZ",
                  "rotateX",
                  "rotateY",
                  "rotateZ",
                  "skewX",
                  "skewY",
                  "backgroundColor",
                  "color",
                  "fontSize",
                  "letterSpacing",
                  "lineHeight",
                  "padding",
                  "margin",
                  "borderWidth",
                  "boxShadow",
                  "textShadow",
                  "filter",
                  "backdropFilter",
                ],
                defaultValue: "opacity",
              },
              endValue: {  // Changed from startValue to endValue
                type: "string",
                displayName: "End Value",
                description: "Final value (e.g., '100px', '1', '0', '45deg', '#ff0000')",
                defaultValue: "1",
              }
            }
          },
        },
      }
    },
    breakpoints: {
      type: "array",
      displayName: "Scroll Animation Breakpoints",
      description: "Define multiple scroll breakpoints with custom CSS properties and easing",
      itemType: {
        type: "object",
        fields: {
          reversable: {
            type: "boolean",
            displayName: "Loop",
            description: "Make scroll animation reversable.",
            defaultValue: true,
          },
          timed: {
            type: "boolean",
            displayName: "Timed Animation",
            description: "Should the animation be based on a duration or Y scroll value",
            defaultValue: false,
          },
          scrollStart: {
            type: "number",
            displayName: "Scroll Start (px)",
            description: "Scroll position where this breakpoint begins",
            defaultValue: 0,
          },
          scrollEnd: {
            type: "number",
            displayName: "Scroll End (px)",
            description: "Scroll position where this breakpoint ends (interpolation mode)",
            defaultValue: 1000,
            hidden: (props) => props.timed,
          },
          pixelDelay: {
            type: "number",
            displayName: "Delay (px)",
            description: "Offset each characters start by a length in pixels.",
            defaultValue: 0,
            hidden: (props) => props.animateChars === false,
          },
          dir: {
            type: "choice",
            options: [
              "up",
              "down",
            ],
            displayName: "Dir",
            description: "Offset each characters start by a length in pixels.",
            defaultValue: "down",
          },
          delay: {
            type: "number",
            displayName: "Delay (ms)",
            description: "How long should this effect wait to animate",
            defaultValue: 0,
            hidden: (props) => props.timed !== true,
          },
          duration: {
            type: "number",
            displayName: "Duration",
            description: "How long should the animation take to complete?",
            defaultValue: 0,

          },
          easingFunction: {
            type: "choice",
            options: [
              "linear",
              "easeInQuad",
              "easeOutQuad",
              "easeInOutQuad",
              "easeInCubic",
              "easeOutCubic",
              "easeInOutCubic",
              "easeInQuart",
              "easeOutQuart",
              "easeInOutQuart",
              "easeInQuint",
              "easeOutQuint",
              "easeInOutQuint",
              "easeInSine",
              "easeOutSine",
              "easeInOutSine",
              "easeInExpo",
              "easeOutExpo",
              "easeInOutExpo",
              "easeInCirc",
              "easeOutCirc",
              "easeInOutCirc",
              "easeInBack",
              "easeOutBack",
              "easeInOutBack",
              "easeInElastic",
              "easeOutElastic",
              "easeInOutElastic",
              "easeInBounce",
              "easeOutBounce",
              "easeInOutBounce",
            ],
            displayName: "Easing Function",
            description: "Timing function for this specific breakpoint",
            defaultValue: "linear",
            hidden: (props) => props.timed,
          },
          styles: {
            type: "array",
            displayName: "Animated Styles",
            description: "Add CSS properties to animate (click + to add more)",
            itemType: {
              type: "object",
              fields: {
                property: {
                  type: "choice",
                  displayName: "CSS Property",
                  description: "Select which CSS property to animate",
                  options: [
                    "top",
                    "left",
                    "right",
                    "bottom",
                    "width",
                    "height",
                    "opacity",
                    "borderRadius",
                    "scale",
                    "rotate",
                    "translateX",
                    "translateY",
                    "translateZ",
                    "scaleX",
                    "scaleY",
                    "scaleZ",
                    "rotateX",
                    "rotateY",
                    "rotateZ",
                    "skewX",
                    "skewY",
                    "backgroundColor",
                    "color",
                    "fontSize",
                    "letterSpacing",
                    "lineHeight",
                    "padding",
                    "margin",
                    "borderWidth",
                    "boxShadow",
                    "textShadow",
                    "filter",
                    "backdropFilter",
                  ],
                  defaultValue: "opacity",
                },
                startValue: {
                  type: "string",
                  displayName: "Start Value",
                  description: "Initial value (e.g., '500px', '1', '0', '180deg', '#0000ff')",
                  defaultValue: "1",
                },
                endValue: {
                  type: "string",
                  displayName: "End Value",
                  description: "Final value (e.g., '500px', '1', '0', '180deg', '#0000ff')",
                  defaultValue: "1",
                },
              },
            },
          },
        },
      },
    },
    clickEffects: {
      type: "array",
      displayName: "Click Effects",
      description: "Define effects that trigger when specific elements are clicked (works alongside scroll animations)",
      itemType: {
        type: "object",
        fields: {
          triggerId: {
            type: "string",
            displayName: "Trigger Element ID",
            description: "ID of the element that triggers this effect when clicked",
            defaultValue: "",
          },
          duration: {
            type: "number",
            displayName: "Duration (ms)",
            description: "How long this effect takes to animate",
            defaultValue: 1000,
          },
          delay: {
            type: "number",
            displayName: "Delay (ms)",
            description: "How long should this effect wait to animate",
            defaultValue: 0,
          },
          easingFunction: {
            type: "choice",
            options: [
              "linear",
              "easeInQuad",
              "easeOutQuad",
              "easeInOutQuad",
              "easeInCubic",
              "easeOutCubic",
              "easeInOutCubic",
              "easeInQuart",
              "easeOutQuart",
              "easeInOutQuart",
              "easeInQuint",
              "easeOutQuint",
              "easeInOutQuint",
              "easeInSine",
              "easeOutSine",
              "easeInOutSine",
              "easeInExpo",
              "easeOutExpo",
              "easeInOutExpo",
              "easeInCirc",
              "easeOutCirc",
              "easeInOutCirc",
              "easeInBack",
              "easeOutBack",
              "easeInOutBack",
              "easeInElastic",
              "easeOutElastic",
              "easeInOutElastic",
              "easeInBounce",
              "easeOutBounce",
              "easeInOutBounce",
            ],
            displayName: "Easing Function",
            description: "Animation timing function for this effect",
            defaultValue: "linear",
          },
          styles: {
            type: "array",
            displayName: "Animated Styles",
            description: "CSS properties to animate when triggered",
            itemType: {
              type: "object",
              fields: {
                property: {
                  type: "choice",
                  displayName: "CSS Property",
                  description: "Which CSS property to animate",
                  options: [
                    "top",
                    "left",
                    "right",
                    "bottom",
                    "width",
                    "height",
                    "opacity",
                    "borderRadius",
                    "scale",
                    "rotate",
                    "translateX",
                    "translateY",
                    "translateZ",
                    "scaleX",
                    "scaleY",
                    "scaleZ",
                    "rotateX",
                    "rotateY",
                    "rotateZ",
                    "skewX",
                    "skewY",
                    "backgroundColor",
                    "color",
                    "fontSize",
                    "letterSpacing",
                    "lineHeight",
                    "padding",
                    "margin",
                    "borderWidth",
                    "boxShadow",
                    "textShadow",
                    "filter",
                    "backdropFilter",
                  ],
                  defaultValue: "opacity",
                },
                endValue: {
                  type: "string",
                  displayName: "End Value",
                  description: "Final value after animation completes",
                  defaultValue: "1",
                },
              },
            },
          },
        },
      },
    },   
    hoverEffects: {
      type: "array",
      displayName: "Hover Effects",
      description: "Define effects that trigger when specific elements are clicked (works alongside scroll animations)",
      itemType: {
        type: "object",
        fields: {
          triggerId: {
            type: "string",
            displayName: "Trigger Element ID",
            description: "ID of the element that triggers this effect when clicked",
            defaultValue: "",
          },
          fullCycle: {
            type: "boolean",
            displayName: "Full Cycle",
            description: "Should the animation reverse imediatly after mouse exit.",
            defaultValue: true,
          },
          duration: {
            type: "number",
            displayName: "Duration (ms)",
            description: "How long this effect takes to animate",
            defaultValue: 1000,
          },
          delay: {
            type: "number",
            displayName: "Delay (ms)",
            description: "How long should this effect wait to animate",
            defaultValue: 0,
          },
          exitDelay: {
            type: "number",
            displayName: "Exit Delay (ms)",
            description: "How long should this effect wait to revert the animation",
            defaultValue: 1000,
          },
          easingFunction: {
            type: "choice",
            options: [
              "linear",
              "easeInQuad",
              "easeOutQuad",
              "easeInOutQuad",
              "easeInCubic",
              "easeOutCubic",
              "easeInOutCubic",
              "easeInQuart",
              "easeOutQuart",
              "easeInOutQuart",
              "easeInQuint",
              "easeOutQuint",
              "easeInOutQuint",
              "easeInSine",
              "easeOutSine",
              "easeInOutSine",
              "easeInExpo",
              "easeOutExpo",
              "easeInOutExpo",
              "easeInCirc",
              "easeOutCirc",
              "easeInOutCirc",
              "easeInBack",
              "easeOutBack",
              "easeInOutBack",
              "easeInElastic",
              "easeOutElastic",
              "easeInOutElastic",
              "easeInBounce",
              "easeOutBounce",
              "easeInOutBounce",
            ],
            displayName: "Easing Function",
            description: "Animation timing function for this effect",
            defaultValue: "linear",
          },
          styles: {
            type: "array",
            displayName: "Animated Styles",
            description: "CSS properties to animate when triggered",
            itemType: {
              type: "object",
              fields: {
                property: {
                  type: "choice",
                  displayName: "CSS Property",
                  description: "Which CSS property to animate",
                  options: [
                    "top",
                    "left",
                    "right",
                    "bottom",
                    "width",
                    "height",
                    "opacity",
                    "borderRadius",
                    "scale",
                    "rotate",
                    "translateX",
                    "translateY",
                    "translateZ",
                    "scaleX",
                    "scaleY",
                    "scaleZ",
                    "rotateX",
                    "rotateY",
                    "rotateZ",
                    "skewX",
                    "skewY",
                    "backgroundColor",
                    "color",
                    "fontSize",
                    "letterSpacing",
                    "lineHeight",
                    "padding",
                    "margin",
                    "borderWidth",
                    "boxShadow",
                    "textShadow",
                    "filter",
                    "backdropFilter",
                  ],
                  defaultValue: "opacity",
                },
                endValue: {
                  type: "string",
                  displayName: "End Value",
                  description: "Final value after animation completes",
                  defaultValue: "1",
                },
              },
            },
          },
        },
      },
    },  
    valueChangeEffects: {
      type: "array",
      displayName: "Value Change Effects",
      description: "Define effects that trigger when the prop value changes (requires parent to be custom code component)",
      itemType: {
        type: "object",
        fields: {
          useOldValue: {
            type: "boolean",
            defaultValue: false,
            displayName: "Use Old Value",
            description: "should element animate with the old value or the new one?",
          },
          resetOnEnd: {
            type: "boolean",
            defaultValue: false,
            displayName: "Reset On End",
            description: "Revert styles to initial styles on animation end."
          },
          duration: {
            type: "number",
            displayName: "Duration (ms)",
            description: "How long this effect takes to animate",
            defaultValue: 1000,
          },
          delay: {
            type: "number",
            displayName: "Delay (ms)",
            description: "How long should this effect wait to animate",
            defaultValue: 0,
          },
          easingFunction: {
            type: "choice",
            options: [
              "linear",
              "easeInQuad",
              "easeOutQuad",
              "easeInOutQuad",
              "easeInCubic",
              "easeOutCubic",
              "easeInOutCubic",
              "easeInQuart",
              "easeOutQuart",
              "easeInOutQuart",
              "easeInQuint",
              "easeOutQuint",
              "easeInOutQuint",
              "easeInSine",
              "easeOutSine",
              "easeInOutSine",
              "easeInExpo",
              "easeOutExpo",
              "easeInOutExpo",
              "easeInCirc",
              "easeOutCirc",
              "easeInOutCirc",
              "easeInBack",
              "easeOutBack",
              "easeInOutBack",
              "easeInElastic",
              "easeOutElastic",
              "easeInOutElastic",
              "easeInBounce",
              "easeOutBounce",
              "easeInOutBounce",
            ],
            displayName: "Easing Function",
            description: "Animation timing function for this effect",
            defaultValue: "linear",
          },
          styles: {
            type: "array",
            displayName: "Animated Styles",
            description: "CSS properties to animate when triggered",
            itemType: {
              type: "object",
              fields: {
                property: {
                  type: "choice",
                  displayName: "CSS Property",
                  description: "Which CSS property to animate",
                  options: [
                    "top",
                    "left",
                    "right",
                    "bottom",
                    "width",
                    "height",
                    "opacity",
                    "borderRadius",
                    "scale",
                    "rotate",
                    "translateX",
                    "translateY",
                    "translateZ",
                    "scaleX",
                    "scaleY",
                    "scaleZ",
                    "rotateX",
                    "rotateY",
                    "rotateZ",
                    "skewX",
                    "skewY",
                    "backgroundColor",
                    "color",
                    "fontSize",
                    "letterSpacing",
                    "lineHeight",
                    "padding",
                    "margin",
                    "borderWidth",
                    "boxShadow",
                    "textShadow",
                    "filter",
                    "backdropFilter",
                  ],
                  defaultValue: "opacity",
                },
                endValue: {
                  type: "string",
                  displayName: "End Value",
                  description: "Final value after animation completes",
                  defaultValue: "1",
                },
              },
            },
          },
        },
      },
    }, 
    distanceEffects: {
      type: "array",
      displayName: "Distance Effects",
      description: "Define effects that trigger when a specific element is a certain distance away",
      itemType: {
        type: "object",
        fields: {
          targetId: {
            type: "string",
            displayName: "Element ID",
            description: "The ID of THIS element",
          },

          distance: {
            type: "number",
            displayName: "Distance (px)",
            description: "How far away should the animation trigger",
            defaultValue: 200,
          },
          qualifyer: {
            type: "choice",
            options: ["===", ">==", "<==", "<", ">", "!=="],
            defaultValue: "===",
            displayName: "Qualifyer",
            description: "How should the animation be triggered based on the distance.",
          },
          duration: {
            type: "number",
            displayName: "Duration (ms)",
            description: "How long this effect takes to animate",
            defaultValue: 1000,
          },
          delay: {
            type: "number",
            displayName: "Delay (ms)",
            description: "How long should this effect wait to animate",
            defaultValue: 0,
          },
          easingFunction: {
            type: "choice",
            options: [
              "linear",
              "easeInQuad",
              "easeOutQuad",
              "easeInOutQuad",
              "easeInCubic",
              "easeOutCubic",
              "easeInOutCubic",
              "easeInQuart",
              "easeOutQuart",
              "easeInOutQuart",
              "easeInQuint",
              "easeOutQuint",
              "easeInOutQuint",
              "easeInSine",
              "easeOutSine",
              "easeInOutSine",
              "easeInExpo",
              "easeOutExpo",
              "easeInOutExpo",
              "easeInCirc",
              "easeOutCirc",
              "easeInOutCirc",
              "easeInBack",
              "easeOutBack",
              "easeInOutBack",
              "easeInElastic",
              "easeOutElastic",
              "easeInOutElastic",
              "easeInBounce",
              "easeOutBounce",
              "easeInOutBounce",
            ],
            displayName: "Easing Function",
            description: "Animation timing function for this effect",
            defaultValue: "linear",
          },
          styles: {
            type: "array",
            displayName: "Animated Styles",
            description: "CSS properties to animate when triggered",
            itemType: {
              type: "object",
              fields: {
                property: {
                  type: "choice",
                  displayName: "CSS Property",
                  description: "Which CSS property to animate",
                  options: [
                    "top",
                    "left",
                    "right",
                    "bottom",
                    "width",
                    "height",
                    "opacity",
                    "borderRadius",
                    "scale",
                    "rotate",
                    "translateX",
                    "translateY",
                    "translateZ",
                    "scaleX",
                    "scaleY",
                    "scaleZ",
                    "rotateX",
                    "rotateY",
                    "rotateZ",
                    "skewX",
                    "skewY",
                    "backgroundColor",
                    "color",
                    "fontSize",
                    "letterSpacing",
                    "lineHeight",
                    "padding",
                    "margin",
                    "borderWidth",
                    "boxShadow",
                    "textShadow",
                    "filter",
                    "backdropFilter",
                  ],
                  defaultValue: "opacity",
                },
                endValue: {
                  type: "string",
                  displayName: "End Value",
                  description: "Final value after animation completes",
                  defaultValue: "1",
                },
              },
            },
          },
        },
      },
    },    
  },
  importPath: "./components/effects/animation/CustomScroll",
  isDefaultExport: false,
});




 // Legacy props for backwards compatibility (hidden when breakpoints are used)
    // startTop: {
    //   type: "string",
    //   displayName: "Start Top",
    //   description: "Initial top position (e.g., '100px', '50vh', '10%')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // startLeft: {
    //   type: "string",
    //   displayName: "Start Left",
    //   description: "Initial left position (e.g., '0px', '25vw')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // startRight: {
    //   type: "string",
    //   displayName: "Start Right",
    //   description: "Initial right position (e.g., '0px', '10vw')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // startBottom: {
    //   type: "string",
    //   displayName: "Start Bottom",
    //   description: "Initial bottom position (e.g., '20px', '5vh')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endTop: {
    //   type: "string",
    //   displayName: "End Top",
    //   description: "Final top position (e.g., '500px', '80vh')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endLeft: {
    //   type: "string",
    //   displayName: "End Left",
    //   description: "Final left position (e.g., '100px', '50vw')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endRight: {
    //   type: "string",
    //   displayName: "End Right",
    //   description: "Final right position (e.g., '100px', '20vw')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endBottom: {
    //   type: "string",
    //   displayName: "End Bottom",
    //   description: "Final bottom position (e.g., '100px', '10vh')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // scrollStart: {
    //   type: "number",
    //   defaultValue: 0,
    //   displayName: "Scroll Start (px)",
    //   description: "Interpolation: animation start | Duration: trigger point",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // scrollEnd: {
    //   type: "number",
    //   defaultValue: 1000,
    //   displayName: "Scroll End (px)",
    //   description: "Scroll position where interpolation completes (interpolation mode only)",
    //   hidden: (props) => props.animationMode !== "interpolation" || (props.breakpoints && props.breakpoints.length > 0),
    // },
    // startOpacity: {
    //   type: "number",
    //   defaultValue: 1,
    //   min: 0,
    //   max: 1,
    //   displayName: "Start Opacity",
    //   description: "Initial opacity (0-1)",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endOpacity: {
    //   type: "number",
    //   defaultValue: 1,
    //   min: 0,
    //   max: 1,
    //   displayName: "End Opacity",
    //   description: "Final opacity (0-1)",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // startBorderRadius: {
    //   type: "string",
    //   displayName: "Start Border Radius",
    //   description: "Initial border radius (e.g., '0px', '50%', '20px')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endBorderRadius: {
    //   type: "string",
    //   displayName: "End Border Radius",
    //   description: "Final border radius (e.g., '50%', '100px', '0px')",
    //   defaultValueHint: "0px",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // startWidth: {
    //   type: "string",
    //   displayName: "Start Width",
    //   description: "Initial width (e.g., '100px', '50vw', '100%')",
    //   defaultValueHint: "auto",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endWidth: {
    //   type: "string",
    //   displayName: "End Width",
    //   description: "Final width (e.g., '200px', '80vw', '50%')",
    //   defaultValueHint: "auto",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // startHeight: {
    //   type: "string",
    //   displayName: "Start Height",
    //   description: "Initial height (e.g., '100px', '50vh', '100%')",
    //   defaultValueHint: "auto",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // endHeight: {
    //   type: "string",
    //   displayName: "End Height",
    //   description: "Final height (e.g., '200px', '80vh', '50%')",
    //   defaultValueHint: "auto",
    //   hidden: (props) => props.breakpoints && props.breakpoints.length > 0,
    // },
    // zIndex: {
    //   type: "number",
    //   defaultValue: 1000,
    //   displayName: "Z-Index",
    //   description: "Stacking order",
    // },